### ISSUE TITLE
can't work with solo address

### ISSUE THREAD

**Issue by witthus** [kilnfi/eth-validator-watcher#89]
HI appreciate to provide this awesome software.I have follow the readme and install everything it requires,but i still get ALL NO DATA from the Grafana panel(i can get the message from the log).

any configuration that i need to set ? also could you please provide an example configuration for loki ?
![screenshot](https://github.com/kilnfi/eth-validator-watcher/assets/18556542/963f9529-dc8d-44c4-9e20-e4d3ffc54004)

**Comment by aimxhaisse** [comment]
Hello,

Thanks for the report! Are you running it locally or under Kubernetes?

Issue is likely in the way your Prometheus source is configured, the model is:

- the watcher exposes its Prometheus metrics link on port 8000
- Prometheus polls data from the watcher periodically, it needs to be configured to do so, if you are running under Kubernetes with the provided chart it should be automatic (the chart exposes the metrics port as 8000)
- is your Prometheus source properly setup on Grafana?

I'm replicating a local setup to improve local setups documentation.

**Comment by witthus** [comment]
thanks for your feedback,yes,i run it locally and i do miss the configuration for Prometheus.I add it now and some of the pannel show the data now.Appreciate for that.

Also,if it possible to provide more detail about loki information? don't know how to configure it but Grafana require for the data source from loki

**Comment by aimxhaisse** [comment]
What I did to have it work locally:

- install promtail/loki
- configure it to watch a folder where log files are stored, I've added the following extra-entry in `/etc/loki/promtail.yaml` under `scrape_configs`:

```
scrape_configs:
- job_name: system
  static_configs:
  - targets:
      - localhost
    labels:
      job: varlogs
      __path__: /var/log/*log
  - targets:
      - localhost
    labels:
      app: ethereum-validator-watcher
      __path__: /var/log/ethereum-watcher/*log
```

Then I make sure my user can write to this log directory:

```
sudo mkdir -p /var/log/ethereum-watcher
sudo chown :mxs /var/log/ethereum-watcher
sudo chmod 775 /var/log/ethereum-watcher
```

Then when I run the watcher, I redirect logs to the directory as follows:

```
eth-validator-watcher --beacon-url $RPC_CL 2>&1 | tee -a /var/log/ethereum-watcher/watcher.log
```

It's clearly a bit tricky to setup, I'll probably find a way to have this under docker with everything  ready directly maybe to simplify local setups.
